wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688155708.450246
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: lr
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: perplexity
      5: 1
      6:
      - 1
num_encoder_layers:
  desc: null
  value: 3
num_decoder_layers:
  desc: null
  value: 3
emb_size:
  desc: null
  value: 192
nhead:
  desc: null
  value: 8
src_vocab_size:
  desc: null
  value: 18000
tgt_vocab_size:
  desc: null
  value: 34000
dim_feedforward:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 96
warmup_steps:
  desc: null
  value: 2000
pad_idx:
  desc: null
  value: 0
